affine_trainable: false
auto_save: true
base_fun_name: identity
ckpt_path: ./model
device: cpu
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 4
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 3
symbolic.funs_name.0:
- - '0'
  - '0'
- - '0'
  - '0'
symbolic_enabled: false
width:
- - 2
  - 0
- - 0
  - 1
