affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - i8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  FAAAAAAAAAA=
grid_eps: 0.02
grid_range:
- -1
- 1
k: 5
mult_arity: 3
round: 0
sb_trainable: true
sp_trainable: true
state_id: 5
symbolic.funs_name.0:
- - '0'
- - '0'
- - '0'
symbolic.funs_name.1:
- - '0'
symbolic_enabled: false
width:
- - 1
  - 0
- - 0
  - 1
- - 1
  - 0
